apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

metadata:
  name: zooby-cluster
  annotations:
    nephio.org/merge: Override

name: zooby-001
networking:
  apiServerPort: 41001
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 42001
