apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  spec:
  chart:
    spec:
    chart: "demo-app"
    version: "0.1.0"
    sourceRef:
      kind: HelmRepository
      name: helm-repository
install:
  disableWait: true
upgrade:
  disableWait: true
interval: 10m
timeout: 2m
values:
  app-value-1: "new-default-value-1"
  app-value-2: "default-value-2"
  app-value-3: "default-value-3"
