apiVersion: porch.kpt.dev/v1alpha1
kind: PackageRevision
metadata:
  creationTimestamp: "2024-03-08T12:53:21Z"
  labels:
    kpt.dev/latest-revision: "true"
  name: management-2eeaaf7c1c41c8202687da7420d2a6a1cdaba051
  namespace: porch-demo
  resourceVersion: 8ac7e823e8ea23ba39fd77816f54568a84818dab
  uid: uid:network-function:v2
spec:
  lifecycle: Published
  packageName: network-function
  repository: management
  revision: v2
  tasks:
  - init:
      description: sample description
    type: init
  - eval:
      config: null
      image: render
      match: {}
    type: eval
  - patch:
      patches:
      - contents: |
          apiVersion: v1
          data:
            app-par-1: default-value-1
            app-par-2: default-value-2
          kind: ConfigMap
          metadata:
            creationTimestamp: null
            name: my-nf
            namespace: porch-demo
        file: test-resource.yaml
        patchType: CreateFile
    type: patch
  - eval:
      config: null
      image: render
      match: {}
    type: eval
  - patch:
      patches:
      - contents: |
          --- test-resource.yaml
          +++ test-resource.yaml
          @@ -2,6 +2,7 @@
           data:
             app-par-1: default-value-1
             app-par-2: default-value-2
          +  app-par-3: default-value-2
           kind: ConfigMap
           metadata:
             creationTimestamp: null
        file: test-resource.yaml
        patchType: PatchFile
    type: patch
  - eval:
      config: null
      image: render
      match: {}
    type: eval
  workspaceName: v2
status:
  publishTimestamp: "2024-03-08T12:53:21Z"
  publishedBy: porch@kpt.dev
  upstreamLock: {}
