apiVersion: topology.nephio.org/v1alpha1
kind: Site

metadata:
  name: edge1

spec:
  siteId: lab/1

---

apiVersion: topology.nephio.org/v1alpha1
kind: Site

metadata:
  name: edge2

spec:
  provisionIfNotFound: true
  merge:
  - apiVersion: kind.x-k8s.io/v1alpha4
    kind: Cluster
    name: edge2
  - apiVersion: metadata.nephio.org/v1alpha1
    kind: Site
    name: edge2

---

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

metadata:
  name: edge2

name: edge2
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 31002
  podSubnet: 10.98.0.0/16
  serviceSubnet: 10.198.0.0/16
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 32002

---

apiVersion: metadata.nephio.org/v1alpha1
kind: Site

metadata:
  name: edge2
  annotations:
    nephio.org/metadata: Postpone

spec:
  provider: Kind
  region: chicago

---

apiVersion: topology.nephio.org/v1alpha1
kind: Site

metadata:
  name: edge3

spec:
  provisionIfNotFound: true
  provisionTemplateId: site/gdce:v1.0.0
  merge:
  - apiVersion: gdce.google.com/v1alpha1
    kind: ToR
    name: edge3

---

apiVersion: gdce.google.com/v1alpha1
kind: ToR

metadata:
  name: edge3

spec: {}

---

apiVersion: topology.nephio.org/v1alpha1
kind: Sites

metadata:
  name: bangalore

spec:
  select:
    metadata:
      Site.cloud: GDC-E
      Site.region: bangalore
